# frozen_string_literal: true

source "https://rubygems.org"

gem 'cucumber',           '5.2'
gem 'rspec',              '3.10'
gem 'httparty',           '0.20.0'
gem 'pry',                '0.14.1'
gem 'net_http_ssl_fix',   '0.0.10'
gem 'openssl',            '2.2'
