# frozen_string_literal: true

source "https://rubygems.org"

gem 'cucumber',           '5.2'
gem 'capybara',           '3.33'
gem 'selenium-webdriver', '3.142.7'
gem 'rspec',              '3.10'
gem 'httparty',           '0.20.0'
gem 'site-prism',         '3.7.3'
gem 'pry',                '0.14.1'
